Repository LMSMinerva/backend, pull requests merged in 2024-12, with the labels that each got.

#8 feat: add testing workflow
  .github/workflows/test.yml
  minerva/manage.py
  minerva/wsgi.py
Labels: enhancement

#11 fix: update WSGI application path in settings
  minerva/requirements.txt
  minerva/settings.py
Labels: bug

#10 docs: add initial README with setup instructions and API documentation
  README.md
Labels: documentation

#12 fix: add localhost to ALLOWED_HOSTS in settings
  minerva/settings.py
Labels: bug

#13 Fix: changes in course model
  minerva/course_category/migrations/0001_initial.py
  minerva/course_category/models/__init__.py
  minerva/course_category/models/course_category.py
  minerva/course_category/models/models.py
  minerva/course_category/serializers/__init__.py
  minerva/course_category/serializers/course_category.py
  minerva/course_category/tests/tests.py
  minerva/course_category/urls.py
  minerva/course_category/views/__init__.py
  minerva/course_category/views/course_category.py
  minerva/courses/migrations/0001_initial.py
  minerva/courses/models/__init__.py
  minerva/courses/models/courses.py
  minerva/courses/models/models.py
  minerva/courses/serializers/__init__.py
  minerva/courses/serializers/courses.py
  minerva/courses/serializers/serializers.py
  minerva/courses/tests/tests.py
  minerva/courses/urls.py
  minerva/courses/views/__init__.py
  minerva/courses/views/courses.py
  minerva/institution/models/__init__.py
  minerva/institution/models/institution.py
  minerva/institution/models/models.py
  minerva/institution/serializers/__init__.py
  minerva/institution/serializers/institution.py
  minerva/institution/tests/tests.py
  minerva/institution/urls.py
  minerva/institution/views/__init__.py
  minerva/institution/views/institution.py
  minerva/settings.py
  poetry.lock
Labels: enhancement
